version: '3.8'

services:
  abo_web:
    build: ./app
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8100:8000
    env_file:
      - ./.env.dev

  abo_mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025
